
MARKET_PLACE_AMAZON = 'amazon'
MARKET_PLACE_AMAZON_ID = 'ASIN'

MARKET_PLACE_FLIPKART = 'flipkart'
MARKET_PLACE_FLIPKART_ID = 'fsn'


MP_ID_MAP = {
    MARKET_PLACE_AMAZON: MARKET_PLACE_AMAZON_ID,
    MARKET_PLACE_FLIPKART: MARKET_PLACE_FLIPKART_ID
}


MARKET_PLACE_LIST = MP_ID_MAP.keys()
MARKET_PLACES_ID_LIST = MP_ID_MAP.values()
